version: "3.9"
services:
  backend:
    image: "nicegsp/springboot-react-fullstack:21.4.2022.9.37.46"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev